set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER icc)
set(CMAKE_CXX_COMPILER icpc)
set(CMAKE_CUDA_COMPILER nvcc)
set(CMAKE_CUDA_HOST_COMPILER icpc)
set(CMAKE_C_FLAGS -D__INTEL_COMPILER=1705)
set(CMAKE_CXX_FLAGS -D__INTEL_COMPILER=1705)
set(CMAKE_CUDA_FLAGS -D__INTEL_COMPILER=1705)


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
