FIND_PATH(FFTW3_INCLUDE_DIR fftw3.h  PATHS ENV CPATH /usr/include /usr/local/include PATH_SUFFIXES fftw3)

FIND_LIBRARY(FFTW3_LIBRARY NAMES fftw3 PATHS ENV LD_LIBRARY_PATH  /usr/lib /usr/local/lib PATH_SUFFIXES)

IF (FFTW3_INCLUDE_DIR AND FFTW3_LIBRARY)
    SET(FFTW3_FOUND TRUE)
ENDIF ( FFTW3_INCLUDE_DIR AND FFTW3_LIBRARY)

IF (FFTW3_FOUND)
    IF (NOT FFTW3_FIND_QUIETLY)
	MESSAGE(STATUS "Found FFTW3: ${FFTW3_LIBRARY}")
    ENDIF (NOT  FFTW3_FIND_QUIETLY)
ELSE(FFTW3_FOUND)
    IF (FFTW3_FIND_REQUIRED)
	IF(NOT FFTW3_INCLUDE_DIR)
	    MESSAGE(FATAL_ERROR "Could not find fftw3 header file!")
	ENDIF(NOT FFTW3_INCLUDE_DIR)

	IF(NOT FFTW3_LIBRARY)
	    MESSAGE(FATAL_ERROR "Could not find fftw3 library file!")
	ENDIF(NOT FFTW3_LIBRARY)
    ENDIF (FFTW3_FIND_REQUIRED)
ENDIF (FFTW3_FOUND)
