FIND_PATH(SYMSPG_INCLUDE_DIR spglib/spglib.h  PATHS ENV CPATH /usr/include /usr/local/include PATH_SUFFIXES spglib)

FIND_LIBRARY(SYMSPG_LIBRARY NAMES symspg PATHS ENV LD_LIBRARY_PATH  /usr/lib /usr/local/lib PATH_SUFFIXES)

IF (SYMSPG_INCLUDE_DIR AND SYMSPG_LIBRARY)
    SET(SYMSPG_FOUND TRUE)
ENDIF ( SYMSPG_INCLUDE_DIR AND SYMSPG_LIBRARY)

IF (SYMSPG_FOUND)
    IF (NOT SYMSPG_FIND_QUIETLY)
	MESSAGE(STATUS "Found SYMSPG: ${SYMSPG_LIBRARY}")
    ENDIF (NOT  SYMSPG_FIND_QUIETLY)
ELSE(SYMSPG_FOUND)
    IF (SYMSPG_FIND_REQUIRED)
	IF(NOT SYMSPG_INCLUDE_DIR)
	    MESSAGE(FATAL_ERROR "Could not find symspg header file!")
	ENDIF(NOT SYMSPG_INCLUDE_DIR)

	IF(NOT SYMSPG_LIBRARY)
	    MESSAGE(FATAL_ERROR "Could not find symspg library file!")
	ENDIF(NOT SYMSPG_LIBRARY)
    ENDIF (SYMSPG_FIND_REQUIRED)
ENDIF (SYMSPG_FOUND)
