# -- Threads
find_package(Threads)
find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    add_definitions(-DUSE_OMP)
endif()

# -- Libconfig++
find_package(CONFIG++ REQUIRED)
add_library(config++ INTERFACE IMPORTED)
set_property(TARGET config++ PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${CONFIG++_INCLUDE_DIR})
set_property(TARGET config++ PROPERTY INTERFACE_LINK_LIBRARIES ${CONFIG++_LIBRARY})

# -- symspg
find_package(SYMSPG REQUIRED)
add_library(symspg INTERFACE IMPORTED)
set_property(TARGET symspg PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${SYMSPG_INCLUDE_DIR})
set_property(TARGET symspg PROPERTY INTERFACE_LINK_LIBRARIES ${SYMSPG_LIBRARY})

# -- hdf5
find_package(HDF5 COMPONENTS CXX REQUIRED)
add_library(hdf5 INTERFACE IMPORTED)
set_property(TARGET hdf5 PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${HDF5_INCLUDE_DIRS} ${HDF5_CXX_INCLUDE_DIR})
set_property(TARGET hdf5 PROPERTY INTERFACE_LINK_LIBRARIES ${HDF5_LIBRARIES} ${HDF5_CXX_LIBRARIES})

# -- CUDA
find_package(CUDA QUIET REQUIRED)
add_library(cuda INTERFACE IMPORTED)
set_property(TARGET cuda PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${CUDA_INCLUDE_DIRS})
set_property(TARGET cuda PROPERTY INTERFACE_LINK_LIBRARIES ${CUDA_LIBRARIES} ${CUDA_CUFFT_LIBRARIES} ${CUDA_CUBLAS_LIBRARIES} ${CUDA_curand_LIBRARY} ${CUDA_cusparse_LIBRARY})


find_package(MKL)
if(MKL_FOUND)
	include_directories(SYSTEM ${MKL_INCLUDE_DIR})
	include_directories(SYSTEM ${FFTW3_INCLUDE_DIR})
	list(APPEND JAMS_LINKER_LIBS ${MKL_LIBRARIES})
	add_definitions(-DUSE_MKL)
endif(MKL_FOUND)

if(NOT MKL_FOUND)
	find_package(FFTW3 REQUIRED)
	include_directories(SYSTEM ${FFTW3_INCLUDE_DIR})
	list(APPEND JAMS_LINKER_LIBS ${FFTW3_LIBRARY})
    find_package(BLAS REQUIRED)
    include_directories(SYSTEM ${BLAS_INCLUDE_DIR})
    list(APPEND JAMS_LINKER_LIBS ${BLAS_LIBRARIES})
endif(NOT MKL_FOUND)
